# Generated by Django 5.0 on 2024-01-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=500)),
                ('dob', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500, unique=True)),
                ('no_exp', models.CharField(max_length=500)),
                ('no_happy_customers', models.CharField(max_length=500)),
                ('no_project_finished', models.CharField(max_length=500)),
                ('no_digital_awards', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=500)),
                ('date_time', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('encryptedvValue', models.CharField(max_length=500)),
                ('verfStatus', models.CharField(max_length=500)),
            ],
        ),
    ]
