# Generated by Django 5.0 on 2024-01-24 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='encryptedvValue',
            new_name='verfKey',
        ),
    ]
