# Generated by Django 5.0 on 2024-01-02 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0002_about_date_time_alter_about_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='name',
            new_name='u_name',
        ),
    ]
